# Generated by Django 5.2.7 on 2025-11-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='オプション：パスワードリセット等に使用', max_length=254, null=True, verbose_name='メールアドレス'),
        ),
    ]
