# Generated by Django 5.2.7 on 2025-11-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encryption_key',
            field=models.CharField(blank=True, help_text='プライバシー保護用の暗号化キー', max_length=255, null=True, verbose_name='暗号化キー'),
        ),
    ]
