# Generated by Django 6.0.1 on 2026-01-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_profile_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='encryption_key',
            field=models.CharField(blank=True, help_text='Reserved for future use', max_length=255, null=True, verbose_name='暗号化キー'),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', 'フリー'), ('starter', 'スターター'), ('pro', 'プロ'), ('school', 'スクール')], default='free', max_length=20, verbose_name='プラン'),
        ),
    ]
