# Generated by Django 6.0.1 on 2026-02-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_encryption_key_alter_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終リマインドメール送信日時'),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_reminder_emails',
            field=models.BooleanField(default=True, verbose_name='リマインドメールを受け取る'),
        ),
    ]
