# Generated by Django 6.0.1 on 2026-03-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_ban_reason_user_banned_at_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tos_agreed_at',
            field=models.DateTimeField(blank=True, help_text='ユーザーが利用規約・プライバシーポリシーに同意した日時', null=True, verbose_name='利用規約同意日時'),
        ),
    ]
