# Generated by Django 6.0.1 on 2026-04-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_tos_agreed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='年齢確認のために使用（課金時の未成年チェック）', null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='user',
            name='parental_consent_at',
            field=models.DateTimeField(blank=True, help_text='未成年ユーザーが課金する際の保護者同意記録', null=True, verbose_name='保護者同意日時'),
        ),
    ]
