# Generated by Django 6.0.1 on 2026-04-09 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_birth_date_parental_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffReviewObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_access_date', models.DateField(help_text='training-data ページに初めてアクセスした日', verbose_name='初回アクセス日')),
                ('pending_reviews', models.IntegerField(default=0, help_text='毎日 +3 累積。編集/削除で -1。', verbose_name='未処理レビュー数')),
                ('is_review_locked', models.BooleanField(default=False, help_text='True の場合、training-data 以外のスタッフ機能を制限', verbose_name='レビューロック')),
                ('last_checked_date', models.DateField(help_text='日次タスクが最後に pending_reviews を加算した日', verbose_name='最終累積チェック日')),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True, verbose_name='最終リマインドメール送信日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_obligation', to=settings.AUTH_USER_MODEL, verbose_name='スタッフユーザー')),
            ],
            options={
                'verbose_name': 'スタッフレビュー義務',
                'verbose_name_plural': 'スタッフレビュー義務',
            },
        ),
    ]
