# Generated by Django 6.0.1 on 2026-04-10 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_staff_review_obligation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDataReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_index', models.IntegerField(help_text='lyrics_training_data.json 内のインデックス (0-based)', verbose_name='データインデックス')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='レビュー日時')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_reviews', to=settings.AUTH_USER_MODEL, verbose_name='レビュー者')),
            ],
            options={
                'verbose_name': '学習データレビュー',
                'verbose_name_plural': '学習データレビュー',
                'unique_together': {('data_index', 'reviewer')},
            },
        ),
    ]
