# Generated by Django 6.0.1 on 2026-04-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_training_data_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdatareview',
            name='trained_at',
            field=models.DateTimeField(blank=True, help_text='このデータが学習に使用された日時（null=未学習）', null=True, verbose_name='学習完了日時'),
        ),
    ]
