# Generated by Django 5.2.7 on 2026-04-12 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_trained_at_to_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDataEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_index', models.IntegerField(help_text='lyrics_training_data.json 内のインデックス (0-based)', verbose_name='データインデックス')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='編集日時')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_edits', to=settings.AUTH_USER_MODEL, verbose_name='編集者')),
            ],
            options={
                'verbose_name': '学習データ編集ログ',
                'verbose_name_plural': '学習データ編集ログ',
            },
        ),
    ]
