# Generated by Django 6.0.1 on 2026-04-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_training_data_edit_log'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingdatareview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trainingdatareview',
            name='data_hash',
            field=models.CharField(db_index=True, default='', help_text='input先頭100文字のSHA256ハッシュ(先頭16文字)', max_length=16, verbose_name='データハッシュ'),
        ),
        migrations.AlterField(
            model_name='trainingdatareview',
            name='data_index',
            field=models.IntegerField(help_text='lyrics_training_data.json 内のインデックス (0-based, 参考値)', verbose_name='データインデックス'),
        ),
        # unique_together は 0017 でデータ変換後に設定
    ]
