# Generated by Django 5.2.7 on 2026-04-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_staffmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(help_text='TrainingDataReviewの全レコードをJSON形式で保存', verbose_name='バックアップデータ')),
                ('record_count', models.IntegerField(verbose_name='レコード数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'レビューバックアップ',
                'verbose_name_plural': 'レビューバックアップ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='trainingdatareview',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
        ),
        migrations.AddField(
            model_name='trainingdatareview',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True の場合、論理削除済み（復元可能）', verbose_name='ソフトデリート'),
        ),
    ]
