# Generated by Django 5.2.7 on 2026-07-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='未成年ユーザーの保護者同意確認メールの送付先', max_length=254, null=True, verbose_name='保護者のメールアドレス'),
        ),
        migrations.AddField(
            model_name='user',
            name='parental_consent_requested_at',
            field=models.DateTimeField(blank=True, help_text='保護者宛ての同意確認メールを送信した日時', null=True, verbose_name='保護者同意リクエスト日時'),
        ),
        migrations.AddField(
            model_name='user',
            name='parental_consent_token',
            field=models.CharField(blank=True, help_text='保護者に送付する同意確認リンクのトークン（使用後は失効）', max_length=64, null=True, verbose_name='保護者同意確認トークン'),
        ),
    ]
