"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# .envファイル
load_dotenv()

# プロジェクトのベースディレクトリ
BASE_DIR = Path(__file__).resolve().parent.parent

# 詳細: https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# セキュリティ警告: 本番環境ではシークレットキーを秘密にしてください
# 本番環境ではSECRET_KEYを環境変数で設定する必要があります
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if os.getenv('RENDER') or os.getenv('PRODUCTION'):
        raise ValueError("SECRET_KEY environment variable is required in production")
    # 開発環境用のフォールバック
    SECRET_KEY = 'django-insecure-dev-only-key-do-not-use-in-production'

# セキュリティ警告: 本番環境ではDEBUGをオンにしないでください
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# 許可するホスト - 明示的に設定、ワイルドカードは使用不可
ALLOWED_HOSTS_STR = os.getenv('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_STR:
    ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS_STR.split(',') if h.strip()]
else:
    # 開発環境のデフォルト
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver']

# 本番環境の検出
if os.getenv('RENDER'):
    RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
    if RENDER_EXTERNAL_HOSTNAME:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# カスタムドメインを追加
ALLOWED_HOSTS.extend(['utamemo.com', 'www.utamemo.com'])


# アプリケーション定義

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'songs',
    'users',
]

# Channels設定
ASGI_APPLICATION = 'myproject.asgi.application'

# Channel Layers設定
# RenderではRedisを使用、ローカルではインメモリを使用
REDIS_URL = os.getenv('REDIS_URL')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myproject.context_processors.language_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# データベース設定

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(conn_max_age=600)


# パスワード検証

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 国際化設定

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# （CSS、JavaScript、画像）

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# メディアファイル
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'users.User'

LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

MUREKA_API_KEY = os.getenv('MUREKA_API_KEY')
USE_MUREKA_API = os.getenv('USE_MUREKA_API', 'False').lower() == 'true'
MUREKA_API_URL = os.getenv('MUREKA_API_URL', 'https://platform.mureka.ai')

# Stripe決済設定
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# 各プランの価格ID（Stripe Dashboardで作成後に設定）
STRIPE_PRICE_IDS = {
    'starter': os.getenv('STRIPE_STARTER_PRICE_ID', ''),  # ¥780/月
    'pro': os.getenv('STRIPE_PRO_PRICE_ID', ''),          # ¥1,900/月
    'school': os.getenv('STRIPE_SCHOOL_PRICE_ID', ''),    # ¥450/月（生徒1人あたり）
}

# 後方互換性のため
STRIPE_PRO_PRICE_ID = STRIPE_PRICE_IDS['pro']

# ========================================
# メール設定
# ========================================
# メールバックエンド（本番環境ではSMTPを使用）
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'UTAMEMO <noreply@utamemo.com>')

# パスワードリセットトークンの有効期限（秒）
PASSWORD_RESET_TIMEOUT = int(os.getenv('PASSWORD_RESET_TIMEOUT', 3600))  # 1時間

# デフォルトの主キーフィールドタイプ
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'songs': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# セッション設定 - DBバックエンドを使用（複数ワーカー環境で確実に同期）
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400 * 14  # 14日間（セキュリティのため短縮）
SESSION_SAVE_EVERY_REQUEST = True  # 毎リクエストでセッションを保存
SESSION_COOKIE_HTTPONLY = True  # JavaScriptからアクセス不可
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF対策
CSRF_COOKIE_SAMESITE = 'Lax'  # CSRF対策

# ========================================
# 本番環境設定
# ========================================
PRODUCTION = os.getenv('PRODUCTION', 'False').lower() == 'true' or os.getenv('RENDER', '') != ''

if PRODUCTION:
    # セキュリティ設定（本番環境）
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HTTPSリダイレクト（Renderはプロキシを使用）
    if os.getenv('RENDER'):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
        SECURE_SSL_REDIRECT = True

# ========================================
# ファイルアップロード制限
# ========================================
# 画像ファイルの最大サイズ（10MB）
MAX_IMAGE_SIZE = int(os.getenv('MAX_IMAGE_SIZE', 10 * 1024 * 1024))
# PDFファイルの最大サイズ（25MB）
MAX_PDF_SIZE = int(os.getenv('MAX_PDF_SIZE', 25 * 1024 * 1024))
# 許可する画像形式
ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/gif', 'image/webp']
# 許可するドキュメント形式
ALLOWED_DOCUMENT_TYPES = ['application/pdf']
# 歌詞の最大文字数
MAX_LYRICS_LENGTH = int(os.getenv('MAX_LYRICS_LENGTH', 5000))
# 歌詞の最小文字数
MIN_LYRICS_LENGTH = int(os.getenv('MIN_LYRICS_LENGTH', 50))

# ========================================
# キューワーカー設定  
# ========================================
# 最大リトライ回数
MAX_GENERATION_RETRIES = int(os.getenv('MAX_GENERATION_RETRIES', 3))
# リトライ間隔（秒）
RETRY_BACKOFF_BASE = int(os.getenv('RETRY_BACKOFF_BASE', 30))
# キューポーリング間隔（秒）
QUEUE_POLL_INTERVAL = int(os.getenv('QUEUE_POLL_INTERVAL', 5))

# ========================================
# API設定
# ========================================
# Mureka APIタイムアウト（秒）- 短縮してユーザー体験を改善
MUREKA_API_TIMEOUT = int(os.getenv('MUREKA_API_TIMEOUT', 60))
# Gemini APIタイムアウト（秒）
GEMINI_API_TIMEOUT = int(os.getenv('GEMINI_API_TIMEOUT', 30))
