# Generated by Django 5.2.7 on 2025-10-29 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='コメント内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'お気に入り',
                'verbose_name_plural': 'お気に入り',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'いいね',
                'verbose_name_plural': 'いいね',
            },
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='歌詞内容')),
                ('original_text', models.TextField(blank=True, verbose_name='元のテキスト')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '歌詞',
                'verbose_name_plural': '歌詞',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('artist', models.CharField(default='AI Generated', max_length=100, verbose_name='アーティスト')),
                ('genre', models.CharField(blank=True, max_length=50, verbose_name='ジャンル')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs/', verbose_name='音声ファイル')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='カバー画像')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='再生時間')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開設定')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='いいね数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '楽曲',
                'verbose_name_plural': '楽曲',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/', verbose_name='画像')),
                ('extracted_text', models.TextField(blank=True, verbose_name='抽出されたテキスト')),
                ('processed', models.BooleanField(default=False, verbose_name='処理済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'アップロード画像',
                'verbose_name_plural': 'アップロード画像',
                'ordering': ['-created_at'],
            },
        ),
    ]
