# Generated by Django 5.2.7 on 2025-10-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, null=True, verbose_name='音声URL'),
        ),
    ]
