# Generated by Django 5.2.7 on 2025-11-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_encrypted',
            field=models.BooleanField(default=False, verbose_name='暗号化済み'),
        ),
    ]
