# Generated by Django 5.2.7 on 2025-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_song_is_encrypted_alter_song_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='generation_status',
            field=models.CharField(choices=[('pending', '待機中'), ('generating', '生成中'), ('completed', '完了'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='生成ステータス'),
        ),
        migrations.AddField(
            model_name='song',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='キュー位置'),
        ),
    ]
