# Generated by Django 5.2.7 on 2025-11-21 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_song_generation_status_song_queue_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='public_content',
            field=models.TextField(blank=True, help_text='公開時のみ復号化されたデータを保存', null=True, verbose_name='公開用歌詞（平文）'),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='public_original_text',
            field=models.TextField(blank=True, help_text='公開時のみ復号化されたデータを保存', null=True, verbose_name='公開用元テキスト（平文）'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='content',
            field=models.TextField(help_text='常に暗号化して保存されます', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='歌詞内容（暗号化）'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='original_text',
            field=models.TextField(blank=True, help_text='OCRで抽出されたテキスト（暗号化）', verbose_name='元のテキスト（暗号化）'),
        ),
    ]
    
# Generated by Django 5.2.7 on 2025-11-21 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_song_generation_status_song_queue_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='public_content',
            field=models.TextField(blank=True, help_text='公開時のみ復号化されたデータを保存', null=True, verbose_name='公開用歌詞（平文）'),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='public_original_text',
            field=models.TextField(blank=True, help_text='公開時のみ復号化されたデータを保存', null=True, verbose_name='公開用元テキスト（平文）'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='content',
            field=models.TextField(help_text='常に暗号化して保存されます', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='歌詞内容（暗号化）'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='original_text',
            field=models.TextField(blank=True, help_text='OCRで抽出されたテキスト（暗号化）', verbose_name='元のテキスト（暗号化）'),
        ),
    ]
