# Generated by Django 5.2.7 on 2025-11-21 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_lyrics_public_content_lyrics_public_original_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='lyrics',
            name='public_content',
        ),
        migrations.RemoveField(
            model_name='lyrics',
            name='public_original_text',
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='content',
            field=models.TextField(help_text='歌詞の本文を入力してください', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='歌詞内容'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='original_text',
            field=models.TextField(blank=True, help_text='OCRで抽出された元のテキスト', verbose_name='元のテキスト'),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開設定'),
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='songs', to='songs.tag', verbose_name='タグ'),
        ),
    ]
