# Generated by Django 5.2.7 on 2025-11-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_tag_remove_lyrics_public_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='vocal_style',
            field=models.CharField(choices=[('female', '女性ボーカル'), ('male', '男性ボーカル')], default='female', max_length=20, verbose_name='ボーカルスタイル'),
        ),
    ]
