# Generated by Django 5.2.7 on 2025-11-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_song_vocal_style'),
    ]

    operations = [
        # 既存のNULL値をFalseに更新（SQLite互換）
        migrations.RunSQL(
            sql="UPDATE songs_song SET is_encrypted = 0 WHERE is_encrypted IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
