# Generated by Django 5.2.7 on 2025-12-17 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_playhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生成完了日時'),
        ),
        migrations.AddField(
            model_name='song',
            name='error_message',
            field=models.TextField(blank=True, help_text='最後に発生したエラーの詳細', null=True, verbose_name='エラーメッセージ'),
        ),
        migrations.AddField(
            model_name='song',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生成開始日時'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['is_public', '-created_at'], name='songs_song_is_publ_1e56b6_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['generation_status'], name='songs_song_generat_66cdd7_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['created_by', '-created_at'], name='songs_song_created_b743c4_idx'),
        ),
    ]
