# Generated by Django 5.2.7 on 2026-01-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_add_error_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mureka_model',
            field=models.CharField(choices=[('mureka-7.6', 'V7.6 (最新・高品質)'), ('mureka-7.5', 'V7.5'), ('mureka-o2', 'O2 (プレミアム)'), ('auto', '自動選択')], default='mureka-7.6', max_length=20, verbose_name='Murekaモデル'),
        ),
    ]
