# Generated by Django 6.0.1 on 2026-01-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_add_reference_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='reference_audio_url',
            field=models.URLField(blank=True, help_text='アップロードされたリファレンス音声のURL', null=True, verbose_name='リファレンス音声URL'),
        ),
        migrations.AlterField(
            model_name='song',
            name='mureka_model',
            field=models.CharField(choices=[('mureka-7.5', 'V7.5 - クリアボーカル・安定'), ('mureka-7.6', 'V7.6 - 高品質・細かい調整可'), ('mureka-o2', 'O2 - 最高品質・プロ向け')], default='mureka-7.5', max_length=20, verbose_name='Murekaモデル'),
        ),
    ]
