# Generated by Django 6.0.1 on 2026-02-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0020_add_mureka_v8_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mureka_model',
            field=models.CharField(choices=[('mureka-v8', 'V8 - 最高品質・感情表現豊か'), ('mureka-o2', 'O2 - 高品質・プロ向け'), ('mureka-7.6', 'V7.6 - スタンダード'), ('mureka-7.5', 'V7.5 - レガシー')], default='mureka-v8', max_length=20, verbose_name='Murekaモデル'),
        ),
    ]
