# Generated by Django 6.0.1 on 2026-02-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0021_v8_default_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='lrc_data',
            field=models.TextField(blank=True, help_text='タイムスタンプ付き歌詞（LRC形式）', null=True, verbose_name='LRC歌詞データ'),
        ),
    ]
