# Generated by Django 6.0.1 on 2026-02-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0022_add_lrc_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='karaoke_audio_url',
            field=models.URLField(blank=True, help_text='Demucsで生成されたインストゥルメンタル音源のURL', null=True, verbose_name='カラオケ音源URL'),
        ),
        migrations.AddField(
            model_name='song',
            name='karaoke_status',
            field=models.CharField(choices=[('none', '未処理'), ('processing', '処理中'), ('completed', '完了'), ('failed', '失敗')], default='none', max_length=20, verbose_name='カラオケ処理ステータス'),
        ),
    ]
