# Generated by Django 6.0.1 on 2026-02-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0023_add_karaoke_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='vocal_style',
            field=models.CharField(choices=[('female', '女性ボーカル'), ('male', '男性ボーカル'), ('vocaloid_female', 'ボカロ風（女性）'), ('vocaloid_male', 'ボカロ風（男性）')], default='female', max_length=20, verbose_name='ボーカルスタイル'),
        ),
    ]
