# Generated by Django 6.0.1 on 2026-03-09 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0024_add_vocaloid_vocal_style'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='デッキ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('source_text', models.TextField(blank=True, help_text='OCRで抽出されたテキストまたは手動入力テキスト', verbose_name='元テキスト')),
                ('card_count', models.PositiveIntegerField(default=0, verbose_name='カード数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('source_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcard_decks', to='songs.uploadedimage', verbose_name='元画像')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_decks', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'フラッシュカードデッキ',
                'verbose_name_plural': 'フラッシュカードデッキ',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=500, verbose_name='用語（表面）')),
                ('definition', models.TextField(verbose_name='定義・説明（裏面）')),
                ('is_selected', models.BooleanField(default=False, help_text='ユーザーがデッキに含めることを選択したカード', verbose_name='選択済み')),
                ('mastery_level', models.IntegerField(choices=[(0, '未学習'), (1, '学習中'), (2, 'もう少し'), (3, '覚えた')], default=0, verbose_name='習熟度')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='songs.flashcarddeck', verbose_name='デッキ')),
            ],
            options={
                'verbose_name': 'フラッシュカード',
                'verbose_name_plural': 'フラッシュカード',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='flashcarddeck',
            index=models.Index(fields=['user', '-updated_at'], name='songs_flash_user_id_f7b204_idx'),
        ),
    ]
