# Generated by Django 6.0.1 on 2026-03-11 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0025_flashcarddeck_flashcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcarddeck',
            name='source_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcard_decks', to='songs.song', verbose_name='元楽曲'),
        ),
    ]
