# Generated by Django 6.0.1 on 2026-03-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0026_add_source_song_to_flashcarddeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='importance',
            field=models.CharField(choices=[('high', '重要'), ('normal', '通常')], default='normal', max_length=10, verbose_name='重要度'),
        ),
    ]
