# Generated by Django 6.0.1 on 2026-03-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0027_add_importance_to_flashcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='vocal_style',
            field=models.CharField(choices=[('女性ボーカル', [('female', '女性ボーカル'), ('female_cute', 'かわいい系女性'), ('female_cool', 'クール系女性'), ('female_powerful', 'パワフル系女性')]), ('男性ボーカル', [('male', '男性ボーカル'), ('male_high', 'ハイトーン系男性'), ('male_low', 'ローボイス系男性'), ('male_rough', 'ワイルド系男性')]), ('特殊スタイル', [('duet', 'デュエット（男女）'), ('choir', 'コーラス / 合唱'), ('whisper', 'ウィスパー / ささやき'), ('child', '子供の声')]), ('ボカロ風', [('vocaloid_female', 'ボカロ風（女性）'), ('vocaloid_male', 'ボカロ風（男性）')])], default='female', max_length=30, verbose_name='ボーカルスタイル'),
        ),
    ]
