# Generated by Django 5.2.7 on 2026-03-31 13:46

import songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0029_add_share_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100, verbose_name='マシン名')),
                ('machine_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('loading', 'Loading Model'), ('training', 'Training'), ('saving', 'Saving'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20, verbose_name='ステータス')),
                ('model_name', models.CharField(blank=True, max_length=200, verbose_name='モデル名')),
                ('current_epoch', models.IntegerField(default=0, verbose_name='現在のエポック')),
                ('total_epochs', models.IntegerField(default=0, verbose_name='総エポック数')),
                ('train_loss', models.FloatField(blank=True, null=True, verbose_name='Train Loss')),
                ('eval_loss', models.FloatField(blank=True, null=True, verbose_name='Eval Loss')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Accuracy')),
                ('gpu_name', models.CharField(blank=True, max_length=100, verbose_name='GPU')),
                ('gpu_memory_used', models.FloatField(blank=True, null=True, verbose_name='VRAM使用量(GB)')),
                ('gpu_memory_total', models.FloatField(blank=True, null=True, verbose_name='VRAM合計(GB)')),
                ('training_config', models.JSONField(blank=True, default=dict, verbose_name='設定')),
                ('log_tail', models.TextField(blank=True, verbose_name='最新ログ')),
                ('error_message', models.TextField(blank=True, verbose_name='エラー')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('api_key', models.CharField(max_length=64, unique=True, verbose_name='APIキー')),
            ],
            options={
                'verbose_name': 'トレーニングセッション',
                'verbose_name_plural': 'トレーニングセッション',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='song',
            name='mureka_model',
            field=models.CharField(choices=[('mureka-v8', 'V8 - 最新モデル')], default='mureka-v8', max_length=20, verbose_name='Murekaモデル'),
        ),
        migrations.AlterField(
            model_name='song',
            name='share_id',
            field=models.CharField(db_index=True, default=songs.models.generate_share_id, help_text='URLに使われるランダムな共有ID', max_length=8, unique=True, verbose_name='共有ID'),
        ),
    ]
