# Generated by Django 5.2.7 on 2026-03-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0030_add_training_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='pending_command',
            field=models.CharField(choices=[('none', 'None'), ('start', 'Start Training'), ('stop', 'Stop Training')], default='none', max_length=20, verbose_name='コマンド'),
        ),
    ]
