# Generated by Django 5.2.7 on 2026-04-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0031_add_pending_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='training_type',
            field=models.CharField(choices=[('lyrics', '歌詞生成LLM'), ('importance', 'ノート重要度LLM')], default='lyrics', max_length=20, verbose_name='学習タイプ'),
        ),
    ]
