# Generated by Django 5.2.7 on 2026-04-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0032_add_training_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='current_step',
            field=models.IntegerField(default=0, verbose_name='現在のステップ'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='total_steps',
            field=models.IntegerField(default=0, verbose_name='総ステップ数'),
        ),
    ]
