# Generated by Django 5.2.7 on 2026-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0033_add_step_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='tunnel_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='トンネルURL'),
        ),
    ]
