# Generated by Django 5.2.7 on 2026-04-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0034_add_tunnel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='eta_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='残り時間(秒)'),
        ),
    ]
