# Generated by Django 5.2.7 on 2026-04-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0035_add_eta_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='wol_mac_address',
            field=models.CharField(blank=True, help_text='例: 04:7C:16:4D:E2:69', max_length=17, verbose_name='WoL MACアドレス'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='wol_target_host',
            field=models.CharField(blank=True, help_text='DDNSホスト名またはグローバルIP', max_length=255, verbose_name='WoL送信先ホスト'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='pending_command',
            field=models.CharField(choices=[('none', 'None'), ('start', 'Start Training'), ('stop', 'Stop Training'), ('start_serve', 'Start Inference Server')], default='none', max_length=20, verbose_name='コマンド'),
        ),
    ]
