# Generated by Django 6.0.1 on 2026-04-13 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0036_add_wol_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('lyrics_instruction', '歌詞生成 Instruction Template'), ('lyrics_system', '歌詞生成 System Prompt')], max_length=50, unique=True, verbose_name='テンプレートキー')),
                ('content', models.TextField(verbose_name='テンプレート本文')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prompts', to=settings.AUTH_USER_MODEL, verbose_name='最終編集者')),
            ],
            options={
                'verbose_name': 'プロンプトテンプレート',
                'verbose_name_plural': 'プロンプトテンプレート',
                'ordering': ['key'],
            },
        ),
    ]
