# Generated by Django 5.2.7 on 2026-04-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0037_add_prompt_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(verbose_name='Instruction')),
                ('input_text', models.TextField(verbose_name='Input (学習テキスト)')),
                ('output_text', models.TextField(verbose_name='Output (生成歌詞)')),
                ('data_hash', models.CharField(db_index=True, help_text='input先頭100文字のSHA256先頭16文字', max_length=16, unique=True, verbose_name='データハッシュ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '学習データ',
                'verbose_name_plural': '学習データ',
                'ordering': ['id'],
            },
        ),
    ]
