# Generated by Django 6.0.1 on 2026-04-17 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0037_add_prompt_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['song', '-created_at'], name='songs_comme_song_id_64e187_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='songs_favor_user_id_197a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['song', 'created_at'], name='songs_like_song_id_3743ae_idx'),
        ),
        migrations.AddIndex(
            model_name='playhistory',
            index=models.Index(fields=['user', '-last_played_at'], name='songs_playh_user_id_8b8204_idx'),
        ),
        migrations.AddIndex(
            model_name='playhistory',
            index=models.Index(fields=['song', '-play_count'], name='songs_playh_song_id_806f70_idx'),
        ),
    ]
