# Generated by Django 5.2.7 on 2026-06-05 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0040_theaterreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(blank=True, help_text='任意で入力できます', max_length=80, verbose_name='お名前')),
                ('desired_show', models.CharField(max_length=120, verbose_name='日曜日の上映会で見たい作品')),
                ('memo', models.TextField(blank=True, help_text='補足があれば入力できます', verbose_name='ひとこと')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回答日時')),
            ],
            options={
                'verbose_name': '劇場アンケート',
                'verbose_name_plural': '劇場アンケート',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='user',
            field=models.ForeignKey(blank=True, help_text='NULLの場合は共有デフォルトテンプレート', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to=settings.AUTH_USER_MODEL, verbose_name='所有ユーザー'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='key',
            field=models.CharField(choices=[('lyrics_instruction', '歌詞生成 Instruction Template'), ('lyrics_system', '歌詞生成 System Prompt')], max_length=50, verbose_name='テンプレートキー'),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(fields=('key', 'user'), name='unique_prompt_per_user'),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('key',), name='unique_shared_prompt'),
        ),
    ]
