# Generated by Django 5.2.7 on 2026-07-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0043_song_provider_and_provider_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mureka_model',
            field=models.CharField(choices=[('mureka-v8', 'V8 - 最新モデル')], default='mureka-v8', max_length=20, verbose_name='Murekaモデル（旧・参照専用）'),
        ),
        migrations.AlterField(
            model_name='song',
            name='provider_model',
            field=models.CharField(blank=True, default='lyria-3-pro-preview', help_text='プロバイダごとの実際のモデル名', max_length=100, verbose_name='プロバイダモデル'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_provider',
            field=models.CharField(choices=[('mureka', 'Mureka'), ('lyria', 'Lyria')], default='lyria', help_text='楽曲生成に使用するAIプロバイダ', max_length=20, verbose_name='楽曲生成プロバイダ'),
        ),
    ]
