# Generated by Django 5.2.7 on 2026-07-30 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0044_switch_default_song_provider_to_lyria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='例: clearnote, kokuyo', unique=True, verbose_name='識別子')),
                ('name', models.CharField(max_length=200, verbose_name='提供元名称')),
                ('contract_reference', models.CharField(blank=True, help_text='覚書の名称・締結日など', max_length=200, verbose_name='契約書/覚書の参照')),
                ('permitted_scope', models.TextField(blank=True, help_text='覚書で許可された用途・データ範囲の要約（第2条相当）', verbose_name='利用許諾範囲')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('deletion_requested_at', models.DateTimeField(blank=True, help_text='提供元から削除依頼を受けた日時（第4条相当）', null=True, verbose_name='削除依頼受領日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'データ提供元',
                'verbose_name_plural': 'データ提供元',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='operated_by',
            field=models.ForeignKey(blank=True, help_text='このマシンを操作するスタッフ。パートナーデータのダウンロード可否判定に使用。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='運用担当者'),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='data_partner',
            field=models.ForeignKey(blank=True, help_text='外部提供データの場合のみ設定。自社生成/ユーザー生成データはNULL。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_data', to='songs.datapartner', verbose_name='データ提供元'),
        ),
        migrations.CreateModel(
            name='DataPartnerAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='許可日時')),
                ('data_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.datapartner', verbose_name='データ提供元')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_data_partner_authorizations', to=settings.AUTH_USER_MODEL, verbose_name='許可者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'データ提供元アクセス許可',
                'verbose_name_plural': 'データ提供元アクセス許可',
                'unique_together': {('data_partner', 'user')},
            },
        ),
        migrations.AddField(
            model_name='datapartner',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, help_text='この提供元のデータを取り扱ってよいと事前通知済みのスタッフ（第3条相当）', related_name='authorized_data_partners', through='songs.DataPartnerAuthorization', through_fields=('data_partner', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='取扱許可メンバー'),
        ),
        migrations.CreateModel(
            name='PartnerDataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', 'インポート'), ('download', 'ダウンロード'), ('delete', '削除')], max_length=20, verbose_name='操作')),
                ('record_count', models.IntegerField(default=0, verbose_name='対象件数')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('data_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_logs', to='songs.datapartner', verbose_name='データ提供元')),
                ('training_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.trainingsession', verbose_name='学習セッション（機械アクセスの場合）')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
            ],
            options={
                'verbose_name': 'パートナーデータアクセスログ',
                'verbose_name_plural': 'パートナーデータアクセスログ',
                'ordering': ['-created_at'],
            },
        ),
    ]
